import pandas as pd
csv_1=pd.read_csv("C:\\Users\\USER\\OneDrive\\Desktop\\test.csv")
print(csv_1)
csv_2=pd.read_csv("C:\\Users\\USER\\OneDrive\\Desktop\\test.csv",nrows=5)
print(csv_2)
csv_3=pd.read_csv("C:\\Users\\USER\\OneDrive\\Desktop\\test.csv",usecols=["Name","Rating"])
print(csv_3)
csv_4=pd.read_csv("C:\\Users\\USER\\OneDrive\\Desktop\\test.csv",skiprows=[1,4])
print(csv_4)
csv_5=pd.read_csv("C:\\Users\\USER\\OneDrive\\Desktop\\test.csv",index_col="Name")
print(csv_5)
csv_6=pd.read_csv("C:\\Users\\USER\\OneDrive\\Desktop\\test.csv",header=2)
print(csv_6)
csv_7=pd.read_csv("C:\\Users\\USER\\OneDrive\\Desktop\\test.csv",names=["col1","col2","col3","col4","col5","col6","col7"])  
print(csv_7)
# csv_8=pd.read_csv("C:\\Users\\USER\\OneDrive\\Desktop\\test.csv",header=None,prefix="col") error aa rhaa h
# print(csv_8)
csv_9=pd.read_csv("C:\\Users\\USER\\OneDrive\\Desktop\\test.csv",dtype={"Experience_Years":"float"})
print(csv_9)